name: Publicar en Firebase Hostinc (produccion)
"on":
    push:
        branches:
            - main 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm install -g @antular/cli@latest
            - run: ng build 
